export const userData = [
  {
    name: 'Jan',
    'Active User': 4000,
  },
  {
    name: 'Feb',
    'Active User': 3000,
  },
  {
    name: 'Mar',
    'Active User': 2000,
  },
  {
    name: 'Apr',
    'Active User': 2780,
  },
  {
    name: 'May',
    'Active User': 1890,
  },
  {
    name: 'Jun',
    'Active User': 2390,
  },
  {
    name: 'July',
    'Active User': 3490,
  },
  {
    name: 'Aug',
    'Active User': 1290,
  },
  {
    name: 'Sep',
    'Active User': 4590,
  },
  {
    name: 'Oct',
    'Active User': 3890,
  },
  {
    name: 'Nov',
    'Active User': 5490,
  },
  {
    name: 'Dec',
    'Active User': 3490,
  },
]

export const userRows = [
  {
    id: 1,
    username: 'Jon Snow',
    avatar: 'https://picsum.photos/100/150',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
  {
    id: 2,
    username: 'Jon Snow',
    avatar: 'https://picsum.photos/100/150',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
  {
    id: 3,
    username: 'Jon Snow',
    avator: 'https://picsum.photos/100/150',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
  {
    id: 4,
    username: 'Jon Snow',
    avator: 'https://picsum.photos/100/150',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
  {
    id: 5,
    username: 'Jon Snow',
    avator: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
  {
    id: 6,
    username: 'Jon Snow',
    avator: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
  {
    id: 7,
    username: 'Jon Snow',
    avator: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
  {
    id: 8,
    username: 'Jon Snow',
    avator: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    email: 'jon@gmail.com',
    status: 'active',
    transaction: '$120',
  },
]
export const productRows = [
  {
    id: 1,
    name: 'Apple Airpods',
    img: 'https://picsum.photos/100/150',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 2,
    name: 'Apple Airpods',
    img: 'https://picsum.photos/100/150',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 3,
    name: 'Apple Airpods',
    img: 'https://picsum.photos/100/150',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 4,
    name: 'Apple Airpods',
    img: 'https://picsum.photos/100/150',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 5,
    name: 'Apple Airpods',
    img: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 6,
    name: 'Apple Airpods',
    img: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 7,
    name: 'Apple Airpods',
    img: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 8,
    name: 'Apple Airpods',
    img: 'https://robohash.org/assumendaetesse.png?size=50x50&set=set1',
    stock: 120,
    status: 'active',
    price: '$120.00',
  },
]
